### ISSUE TITLE
bin file is absent from the downloaded zip when the keyboard layout has been changed

### ISSUE THREAD

**Issue by Iris3Meow** [kiibohd/configurator#35] opened 2017-11-05 21:52 UTC
When I change the keymap even a little, the downloaded zip file does not contain the bin file needed for the flash. 
The keymap change I am currently trying is changing the function of the base layer PgUp key to Vol Up  and the PgDn key to Vol Dn. 
I then assigned the Pg Up and Pg Dn functions on the respective buttons on Layer 1.

![capture](https://user-images.githubusercontent.com/33403306/32419542-a257b402-c249-11e7-94ef-65e2fa830eca.JPG)

**Comment by Iris3Meow** [comment] 2017-11-05 21:53
This issue has not been fixed as of 0.2.0 I have tried just now
![capture](https://user-images.githubusercontent.com/33403306/32419562-d5d60c2a-c249-11e7-8897-4af042fc6d6e.JPG)

**Comment by jbondeson** [comment] 2017-11-05 21:59
@Iris3Meow compilation failed due to an error. in this case it's a blank animation in your file it's `white` if you were to delete it your compilation should succeed. 

The "success" message is incorrect and will be addressed by #25 and I opened #36 to address the root cause of this compilation failure.

**Closed by jbondeson** 2017-11-05 21:59 UTC

**Comment by Iris3Meow** [comment] 2017-11-05 22:05
@jbondeson 
So 2 questions.
1. how did you know i had a layer labeld white?
2. how else am I supposed to get a colorscheme where the keyboard has white light and does a fingerprint animation of a random color upon press? I don't see any option where the user can create LED animations

Thanks for answering my question btw!
