### ISSUE TITLE
Fingerprint visualization doesn't work when keys are pressed very quick.

### ISSUE THREAD

**Issue by spirosag** [kiibohd/configurator#64] opened 2017-11-30 14:27 UTC
When a 2nd key is pressed after the first one, the 2nd key doesn't light up when using the default fingerprint visualization

**Comment by johanntang** [comment] 2017-12-01 00:49
Dupe of https://github.com/kiibohd/configurator/issues/64

**Comment by spirosag** [comment] 2017-12-01 07:16
@johanntang #64 is this one :) I guess it's a dupe of some other ticket

**Comment by jbondeson** [comment] 2017-12-01 14:27
It's a dupe of #45

**Closed by jbondeson** 2017-12-01 14:27 UTC
Labels: duplicate
