### ISSUE TITLE
Color shift with LED brightness

### ISSUE THREAD

**Issue by clintiepoo** [kiibohd/configurator#49] opened 2017-11-10 12:31 UTC
LEDs change color with the brightness level.  Orange at high brightness looks yellow at low brightness.  Can this be compensated for in the firmware?

**Comment by jbondeson** [comment] 2017-11-10 15:49
Duplicate of #39 

(and yes, we're going to be looking into it)

**Closed by jbondeson** 2017-11-10 15:49 UTC
