### ISSUE TITLE
Two/Three Button Combos don't light up

### ISSUE THREAD

**Issue by Diserasta** [kiibohd/configurator#68] opened 2017-12-05 01:54 UTC
Using a very simple two-tone fingerprint of white to black (off), certain key combos don't light up the second/third keys.

For example Ctrl+T results in both Control and T lighting up, but if you press Ctrl+W, the W doesn't light up.
Key Combos that don't work:

- Ctrl+W
- Ctrl+Alt+Del (Alt doesn't light up, Del does)
- Ctrl+Tab (Alt+Tab works weirdly)

I can't see any logic to why this happens unless it's some sort of buffering issue based on how the K-Type does the scanlines for its animations.

**Comment by jbondeson** [comment] 2017-12-05 03:37
Duplicate of #45.

**Closed by jbondeson** 2017-12-05 03:37 UTC
